[project]
name = "pyapisample"
version = "0.1.0"
description = "An API testing sample harness written in Python"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "pytest>=9.0.3",
    "pytest-xdist>=3.8.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.10",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN401", "D203", "D213"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101", "PLR2004", "D1", "ANN"]
